/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard aggregate data */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get motivational board items */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks for a goal */
        get: operations["listTasks"];
        put?: never;
        /** Create a task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a task complete */
        post: operations["completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a task explanation (skipped/failed) */
        post: operations["explainTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI-assisted goal proposal */
        post: operations["proposeGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a goal */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskStatus: "pending" | "completed" | "skipped";
        /** @enum {string} */
        TaskRepeatFrequency: "none" | "daily" | "weekly" | "monthly";
        /** @enum {string} */
        ExplanationReason: "couldnt" | "forgot" | "chose_not_to";
        /** @enum {string} */
        BoardItemType: "win" | "milestone";
        /** @enum {string} */
        MilestoneKind: "streak_7" | "streak_30" | "goal_completed";
        TaskSummary: {
            id: string;
            title: string;
            goalId: string;
            status: string;
            dueDate?: string | null;
        };
        GoalSummary: {
            id: string;
            title: string;
            category: string;
            currentStreak: number;
            longestStreak: number;
            todayTaskCount: number;
            completedTodayCount: number;
        };
        TodayProgress: {
            completed: number;
            total: number;
        };
        DashboardData: {
            todaysTasks: components["schemas"]["TaskSummary"][];
            /** @description Completion counts indexed Mon=0 … Sun=6 */
            weekCompletions: number[];
            goals: components["schemas"]["GoalSummary"][];
            todayProgress: components["schemas"]["TodayProgress"];
        };
        BoardItem: {
            id: string;
            type: components["schemas"]["BoardItemType"];
            taskTitle?: string | null;
            goalTitle?: string | null;
            goalCategory?: string | null;
            moodScore?: number | null;
            reflection?: string | null;
            mentorReaction?: string | null;
            mediaUrl?: string | null;
            milestoneKind?: components["schemas"]["MilestoneKind"];
            streakDays?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        TaskItem: {
            id: string;
            goalId: string;
            title: string;
            description?: string | null;
            status: components["schemas"]["TaskStatus"];
            dueDate?: string | null;
            repeatFrequency: components["schemas"]["TaskRepeatFrequency"];
            occurrenceIndex: number;
            parentTaskId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTaskPayload: {
            title: string;
            goalId: string;
            description?: string;
            dueDate?: string;
            repeatFrequency?: components["schemas"]["TaskRepeatFrequency"];
        };
        CompleteTaskPayload: {
            moodScore: number;
            reflection?: string;
            memoryPictureId?: string;
            personalityId?: string;
        };
        ExplainTaskPayload: {
            reason: components["schemas"]["ExplanationReason"];
            freeText?: string;
            personalityId?: string;
        };
        TaskCompletion: {
            id: string;
            taskId: string;
            moodScore: number;
            reflection?: string | null;
            memoryPictureId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        TaskExplanation: {
            id: string;
            taskId: string;
            reason: components["schemas"]["ExplanationReason"];
            freeText?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        TaskCompletionResponse: {
            data: components["schemas"]["TaskCompletion"];
            mentorReaction?: string | null;
            safetyFlag?: boolean | null;
        };
        TaskExplanationResponse: {
            data: components["schemas"]["TaskExplanation"];
            mentorReaction?: string | null;
            safetyFlag?: boolean | null;
        };
        GoalProposal: {
            title: string;
            description?: string | null;
            costText?: string | null;
            benefitText?: string | null;
            failureText?: string | null;
            deadline?: string | null;
            repeatRule?: Record<string, never> | null;
            category?: string | null;
        };
        CreateGoalPayload: {
            title: string;
            description?: string;
            costText?: string;
            benefitText?: string;
            failureText?: string;
            deadline?: string;
            repeatRule?: Record<string, never>;
            category?: string;
            mentorId?: number;
            stakeAmount?: number;
        };
        CreateGoalResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardItem"][];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                goalId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItem"][];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskPayload"];
            };
        };
        responses: {
            /** @description Created task */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItem"];
                };
            };
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteTaskPayload"];
            };
        };
        responses: {
            /** @description Completion result with optional mentor reaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCompletionResponse"];
                };
            };
        };
    };
    explainTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainTaskPayload"];
            };
        };
        responses: {
            /** @description Explanation result with optional mentor reaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskExplanationResponse"];
                };
            };
        };
    };
    proposeGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    raw: string;
                };
            };
        };
        responses: {
            /** @description AI-structured goal proposal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalProposal"];
                };
            };
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalPayload"];
            };
        };
        responses: {
            /** @description Created goal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGoalResponse"];
                };
            };
        };
    };
}
